export const CategoryData = [
    { id: 1, name: 'Gin' },
    { id: 2, name: 'Whisky' },
    { id: 3, name: 'Ron' },
    { id: 4, name: 'Tequila' },
    { id: 5, name: 'Vodka' },
    { id: 6, name: 'Otros' },
];

export const ProductsData = [
    {
        category: 'Gin',
        products: [
            {
                id: 3,
                promoTag: true,
                rating: 4.9,
                reviews: 412,
                title: 'Gin Tropical',
                price: 'Bs 29.99',
            },
            {
                id: 16,
                promoTag: false,
                rating: 4.7,
                reviews: 292,
                title: 'Gin Clásico',
                price: 'Bs 28.50',
            },
        ],
    },
    {
        category: 'Whisky',
        products: [
            {
                id: 2,
                promoTag: false,
                rating: 4.5,
                reviews: 256,
                title: 'Whisky Ahumado',
                price: 'Bs 42.75',
            },
            {
                id: 13,
                promoTag: true,
                rating: 4.9,
                reviews: 421,
                title: 'Whisky Escocés Puro Malta',
                price: 'Bs 40.25',
            },
        ],
    },
    {
        category: 'Ron',
        products: [
            {
                id: 4,
                promoTag: false,
                rating: 4.7,
                reviews: 198,
                title: 'Ron Especiado',
                price: 'Bs 38.50',
            },
            {
                id: 17,
                promoTag: true,
                rating: 4.5,
                reviews: 238,
                title: 'Ron Añejo',
                price: 'Bs 34.75',
            },
        ],
    },
    {
        category: 'Tequila',
        products: [
            {
                id: 6,
                promoTag: false,
                rating: 4.8,
                reviews: 301,
                title: 'Tequila Reposado',
                price: 'Bs 45.25',
            },
            {
                id: 18,
                promoTag: false,
                rating: 4.9,
                reviews: 410,
                title: 'Tequila Añejo',
                price: 'Bs 41.80',
            },
        ],
    },
    {
        category: 'Vodka',
        products: [
            {
                id: 5,
                promoTag: true,
                rating: 4.6,
                reviews: 367,
                title: 'Vodka Frutas del Bosque',
                price: 'Bs 31.80',
            },
        ],
    },
    {
        category: 'Otros',
        products: [
            {
                id: 1,
                promoTag: true,
                rating: 4.8,
                reviews: 309,
                title: 'Martini Elegante',
                price: 'Bs 35.00',
            },
            {
                id: 7,
                promoTag: true,
                rating: 4.7,
                reviews: 289,
                title: 'Cerveza Artesanal IPA',
                price: 'Bs 22.50',
            },
            {
                id: 8,
                promoTag: false,
                rating: 4.5,
                reviews: 245,
                title: 'Licor de Chocolate',
                price: 'Bs 27.75',
            },
            {
                id: 9,
                promoTag: true,
                rating: 4.9,
                reviews: 432,
                title: 'Coctel Mojito Refrescante',
                price: 'Bs 33.99',
            },
            {
                id: 10,
                promoTag: false,
                rating: 4.6,
                reviews: 375,
                title: 'Agua Mineral Premium',
                price: 'Bs 20.50',
            },
            {
                id: 11,
                promoTag: true,
                rating: 4.8,
                reviews: 314,
                title: 'Champagne Elegancia',
                price: 'Bs 49.00',
            },
            {
                id: 12,
                promoTag: false,
                rating: 4.7,
                reviews: 278,
                title: 'Sidra Tradicional',
                price: 'Bs 24.75',
            },
            {
                id: 14,
                promoTag: false,
                rating: 4.6,
                reviews: 360,
                title: 'Cóctel Piña Colada',
                price: 'Bs 37.80',
            },
            {
                id: 15,
                promoTag: true,
                rating: 4.8,
                reviews: 305,
                title: 'Cerveza Lager Premium',
                price: 'Bs 23.99',
            },
            {
                id: 19,
                promoTag: true,
                rating: 4.6,
                reviews: 355,
                title: 'Vino Tinto Reserva',
                price: 'Bs 46.50',
            },
            {
                id: 20,
                promoTag: false,
                rating: 4.8,
                reviews: 309,
                title: 'Licor de Café',
                price: 'Bs 32.00',
            },
        ],
    },
];